.TH "src Directory Reference" 3 "Wed Dec 23 2015" "Face_detection" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBface_detect\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimage_publish\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimgsubcriber\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwebcam_video_show\&.cpp\fP"
.br
.in -1c
