.TH "src/image_publish.cpp" 3 "Wed Dec 23 2015" "Face_detection" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/image_publish.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <image_transport/image_transport\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <opencv2/imgproc/imgproc\&.hpp>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const float \fBkScaleFactor\fP = 1\&.0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 17 of file image_publish\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const float kScaleFactor = 1\&.0"

.PP
Definition at line 15 of file image_publish\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Face_detection from the source code\&.
