.TH "src/imgsubcriber.cpp" 3 "Wed Dec 23 2015" "Face_detection" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/imgsubcriber.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <image_transport/image_transport\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBimageCallback\fP (const sensor_msgs::ImageConstPtr &msg)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void imageCallback (const sensor_msgs::ImageConstPtr &msg)"

.PP
Definition at line 15 of file imgsubcriber\&.cpp\&.
.SS "int main (intargc, char **argv)"

.PP
Definition at line 32 of file imgsubcriber\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Face_detection from the source code\&.
