.TH "src/webcam_video_show.cpp" 3 "Wed Dec 23 2015" "Face_detection" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/webcam_video_show.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ros/ros\&.h>\fP
.br
\fC#include <image_transport/image_transport\&.h>\fP
.br
\fC#include <opencv2/highgui/highgui\&.hpp>\fP
.br
\fC#include <cv_bridge/cv_bridge\&.h>\fP
.br
\fC#include <sstream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char **argv)"

.PP
Definition at line 12 of file webcam_video_show\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Face_detection from the source code\&.
